// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaChJejOmczcKCpPv9kzfTbaIEI4Irw-s',
    appId: '1:698477000967:web:ac17ca8ff9877d9523eda2',
    messagingSenderId: '698477000967',
    projectId: 'gano-15bfd',
    authDomain: 'gano-15bfd.firebaseapp.com',
    storageBucket: 'gano-15bfd.appspot.com',
    measurementId: 'G-Y22G46WJDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuJ2-A8vfrA2qXFd2GwM1F-KIjuPS9Dlo',
    appId: '1:698477000967:android:7addc0c8834177d823eda2',
    messagingSenderId: '698477000967',
    projectId: 'gano-15bfd',
    storageBucket: 'gano-15bfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKhzmUIxTImqvmjHLoSo59tjMW_lIt2z4',
    appId: '1:698477000967:ios:0be567c0c7bf0b9f23eda2',
    messagingSenderId: '698477000967',
    projectId: 'gano-15bfd',
    storageBucket: 'gano-15bfd.appspot.com',
    iosBundleId: 'com.softwareGano.gano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKhzmUIxTImqvmjHLoSo59tjMW_lIt2z4',
    appId: '1:698477000967:ios:0be567c0c7bf0b9f23eda2',
    messagingSenderId: '698477000967',
    projectId: 'gano-15bfd',
    storageBucket: 'gano-15bfd.appspot.com',
    iosBundleId: 'com.softwareGano.gano',
  );
}
